### ISSUE TITLE
Desktop: Services>Pre-Pro Services, Content block titles not displaying

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#13]
The content block titles are not displaying on each block of content, despite showing up in the CMS. 

CMS: ![screen shot 2016-11-16 at 1 47 44 pm](https://cloud.githubusercontent.com/assets/16961015/20360841/47e8b866-ac03-11e6-80a0-2bf22005740c.png)

Page: 
![screen shot 2016-11-16 at 1 48 23 pm](https://cloud.githubusercontent.com/assets/16961015/20360855/5e6aa9aa-ac03-11e6-952e-dc474d7e0496.png)

**Comment by jeffbinando** [comment]
These were not hooked up at the time. They should be good to go now.
