### ISSUE TITLE
Desktop: Systems - at a glance descriptions missing on boxes

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#15]
This should be the same template as "Services" so we should have the descriptions as well above "learn more." 

![screen shot 2016-11-16 at 3 47 04 pm](https://cloud.githubusercontent.com/assets/16961015/20365181/f8a9cd38-ac13-11e6-8e2b-90c6835fbed7.png)

**Comment by jeffbinando** [comment]
Yeah i noticed that today as well. Do we have these in the content?

**Comment by kimmouser** [comment]
I thought I clicked reply yesterday, but yes we do have these in content.
