### ISSUE TITLE
Mobile: Image cut-off under completed projects section across site

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#17]
Looks like there is an odd image crop appearing beneath project name. 

![screen shot 2016-11-16 at 4 04 23 pm](https://cloud.githubusercontent.com/assets/16961015/20365826/714a00da-ac16-11e6-94a2-5a83c0f85a69.png)

**Comment by jeffbinando** [comment]
Clint is working on the Sliders
