### ISSUE TITLE
Menu Bar out of order

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#19]
Order on menu bar doesn't follow design. Should be Company, Services, Systems, Products, Portfolio, Contact. Not sure I can change through CMS. 

![screen shot 2016-11-17 at 10 28 11 am](https://cloud.githubusercontent.com/assets/16961015/20395344/929f58e4-acb0-11e6-9177-6c6d2a70f5be.png)

**Comment by jeffbinando** [comment]
Ah. Design must have changed since i had initially created the menu and I didn't notice.
