### ISSUE TITLE
Project page > Completed Projects list - text spacing issue

### ISSUE THREAD

**Issue by nicolegreen-chemistry** [ChemistryPittsburgh/ecms#22]
The project text (name & type) are too close to the next consecutive project. This might confuse users that the name/type belongs to the next project image instead of the proper one. Could we add more space between the project label and the next project image?

![completedprojects-text](https://cloud.githubusercontent.com/assets/20845047/20445176/00f9ed26-ada2-11e6-9952-39719c13dd5a.png)

**Comment by jeffbinando** [comment]
This screenshot was taken before this section was completed.
