### ISSUE TITLE
Question: Project page > Completed Projects list - what are these arrows for?

### ISSUE THREAD

**Issue by nicolegreen-chemistry** [ChemistryPittsburgh/ecms#30]
There are no labels or any other hints to provide context for what these arrows are supposed to do. They only appear next to this one project and nowhere else along the list.

![project-randoarrows](https://cloud.githubusercontent.com/assets/20845047/20446368/327b7a86-ada7-11e6-986a-5e91bf54fb56.png)

**Comment by jeffbinando** [comment]
It's an image slider. It was under development when you took that screenshot. It's functional now.
