### ISSUE TITLE
Question: No News link in main nav?

### ISSUE THREAD

**Issue by nicolegreen-chemistry** [ChemistryPittsburgh/ecms#31]
Disclaimer: I dunno if this is the client's preference or not.
The only way a user can get to News & Announcements is to follow a link from the section placed at the bottom of every page. While it’s still accessible, it’s too easy to forget that news is a part of the site, since it’s not pushed for attention in the main nav.

**Comment by jeffbinando** [comment]
This is how the sitemap and designs were laid out. This would be a question for design.
