### ISSUE TITLE
Project Details - hide icon if no content

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#42]
We talked about the ability to hide any of the icons if there is missing content (i.e., no architect)

![screen shot 2016-11-22 at 1 21 35 pm](https://cloud.githubusercontent.com/assets/16961015/20536326/9fe1b240-b0b6-11e6-86c7-9ebdbadf3b56.png)

**Comment by jeffbinando** [comment]
general contractor and architect are optional
product/system toggle
