### ISSUE TITLE
Project Portfolio: Build Filters

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#43]
Client to provide direction on filters.

**Comment by jeffbinando** [comment]
We need the the information about this from the client ASAP

**Comment by kimmouser** [comment]
Per Client: We would like to be able to filter by Product, System, and Industry and have the ability to show both the product and system at the same time with separate icons in the portfolio view.  As with the other icons, If the information is not populated the icon wont show.
