### ISSUE TITLE
Search Results: Look at importance of search results

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#51]
They want actual systems pages to show up before downloads. Is that possible? 

![screen shot 2016-11-22 at 1 44 36 pm](https://cloud.githubusercontent.com/assets/16961015/20537139/f4af5f40-b0b9-11e6-9151-f88272b67b60.png)

**Comment by jeffbinando** [comment]
I'm going to need to do some research into a plugin that will be able to change the priority of search results.

**Comment by jeffbinando** [comment]
I added a plugin that has more advanced search options and allows for more customization but in the end it still returns results based off of relevance so if an interior service page has more relevant content to the search than the parent service page, the interior page will appear first in the results.
