### ISSUE TITLE
Pre-Pro: Tighten Up Margins

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#52]
Can we tighten up the margins on this, per client request? 

![screen shot 2016-11-22 at 1 48 40 pm](https://cloud.githubusercontent.com/assets/16961015/20537246/66774c28-b0ba-11e6-9a5b-0fdabb018c83.png)

**Comment by jeffbinando** [comment]
Changed the padding from 70px to 45px.
