### ISSUE TITLE
Product-Custom Arch Flashing, Bulleted List

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#53]
Client had requested ability to make a two column bulleted list if possible. 

![screen shot 2016-11-22 at 1 54 52 pm](https://cloud.githubusercontent.com/assets/16961015/20537488/5be20608-b0bb-11e6-87d4-49e55f76d36f.png)

**Comment by jeffbinando** [comment]
They can now have multiple columns of lists that they can setup in the cms
