### ISSUE TITLE
Projects>Frostburg State, title needs bumped up in blue bar

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#56]
![screen shot 2016-11-28 at 11 39 05 am](https://cloud.githubusercontent.com/assets/16961015/20677088/f2bdc2f8-b55f-11e6-8000-e5d73164ce9b.png)

Looks fine on all other projects - just noticed it here.

**Comment by jeffbinando** [comment]
I'll need to consult mike on what the best course of action is here since this length of content was not accounted for in the design. especially in mobile.

**Comment by jeffbinando** [comment]
Changed title to "Frostburg State University" and added overview text with the full title.
