### ISSUE TITLE
Services>Secure Scan, Different Font Color

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#58]
![screen shot 2016-11-28 at 11 50 21 am](https://cloud.githubusercontent.com/assets/16961015/20677377/e0343292-b560-11e6-91b7-30af0ed00336.png)
http://ecms.chemistry.digital:8080/service/secure-scan-3d-laser-scanning/

Does the font color look different to you, between first and second paragraph? Or maybe the top paragraph is bolded?

**Comment by jeffbinando** [comment]
It's all the same color. #646464
