### ISSUE TITLE
IE: Issue with boxes 

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#66]
![unknown](https://cloud.githubusercontent.com/assets/16961015/20713298/bfb239e6-b615-11e6-82b0-26d0fd713169.jpeg)

Apparently this is happening for them when they return to a previous page.

**Comment by jeffbinando** [comment]
@kimmouser  I'm not seeing this in IE 9, 10 or edge. I tried duplicating it by going to the portfolio page, clicking on a project then clicking the back button in the browser to return to the portfolio. 

Unable to replicate. They'll need to provide the exact steps and what version of IE they're using.

**Comment by jeffbinando** [comment]
@nicolegreen-chemistry if you have time could you please try to see if you can replicate this?

**Comment by nicolegreen-chemistry** [comment]
I checked it out at the QA station, which is running IE 11 (ver. 11.0.9600.18524) on Windows 7, and it did not replicate this issue.

**Comment by kimmouser** [comment]
I sent an email to the client to ask for a screenshot as well as IE version.

**Comment by jeffbinando** [comment]
@kimmouser Can you also ask them to detail the exact steps they did to cause the error?

**Comment by kimmouser** [comment]
Ok, per the client: I clicked on the Systems tab, then “learn more” under EC-150 (which took me to that page), then hit the back button on the browser. This is what happens. Again, I have IE 11.

**Comment by jeffbinando** [comment]
But the screenshot she is showing is the project page..... So that could not have been the same instance as what she described.

**Comment by kimmouser** [comment]
So I emailed her this and she said she sent the wrong screenshot. Hmm. Here you go:

![unknown-2](https://cloud.githubusercontent.com/assets/16961015/20772275/dc434518-b71a-11e6-9b0e-2fcffa682173.jpeg)

**Comment by jeffbinando** [comment]
Yep still unable to replicate so not really sure what we can do here. I have an idea of what would cause this but it's not happening on any browser i try it in so i can't say for sure.
