### ISSUE TITLE
Build Rep locator on Contact Page

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#70]
![screen shot 2016-11-30 at 12 20 39 pm](https://cloud.githubusercontent.com/assets/16961015/20763298/6f3bd4ee-b6f7-11e6-98ff-b9e3d7a6dc0b.png)

Noticed it was missing today..

**Comment by jeffbinando** [comment]
Right so for this I never got any content for the reps or how exactly this was supposed to function.
