### ISSUE TITLE
Desktop: Products>Custom Architectural Flashings, Bullets

### ISSUE THREAD

**Issue by kimmouser** [ChemistryPittsburgh/ecms#8]
Bullets are not appearing correctly. Are we able to utilize two types of bullets here with an indent? 

![screen shot 2016-11-16 at 12 58 32 pm](https://cloud.githubusercontent.com/assets/16961015/20359106/68c57530-abfc-11e6-9c71-7f051eec47af.png)

**Comment by jeffbinando** [comment]
Bullets were never part of the design for this text area. I'll need to look and see what we're able to add.

**Comment by jeffbinando** [comment]
I updated the text area so that they can select a bulleted list when entering the content. 
Nicole is going through and updating the text.

**Comment by nicolegreen-chemistry** [comment]
The bulleted lists should be updated now.
